package com.philemonworks.selfdiagnose.dashboard.rest
{
	// RemoteProviderService is generated by RestWorks FlexGenerator on Mon Apr 30 20:10:36 CEST 2007

	import com.philemonworks.flex.Command;
	import com.philemonworks.flex.RestClient;
	
	public class RemoteProviderService {
		/**
		 * @param providerXml : String
		 * @param replyHandler : Function
		 */
		public function save(providerXml:String, replyHandler:Function):void {
			var restclient:RestClient = new RestClient()
			var cmd:Command = new Command("save")
			cmd.setParameter("providerXml",providerXml)				
			restclient.remoteExecute(cmd,"providers/command",replyHandler)
		}
		/**
		 * @param providerID : String
		 * @param replyHandler : Function
		 */
		public function run(providerID:String, replyHandler:Function):void {
			var restclient:RestClient = new RestClient()
			var cmd:Command = new Command("run")
			cmd.setParameter("providerID",providerID)				
			restclient.remoteExecute(cmd,"providers/command",replyHandler)
		}
		/**
		 * @param providerID : String
		 * @param replyHandler : Function
		 */
		public function remove(providerID:String, replyHandler:Function):void {
			var restclient:RestClient = new RestClient()
			var cmd:Command = new Command("remove")
			cmd.setParameter("providerID",providerID)				
			restclient.remoteExecute(cmd,"providers/command",replyHandler)
		}
		/**
		 * @param providerID : String
		 * @param replyHandler : Function
		 */
		public function copy(providerID:String, replyHandler:Function):void {
			var restclient:RestClient = new RestClient()
			var cmd:Command = new Command("copy")
			cmd.setParameter("providerID",providerID)				
			restclient.remoteExecute(cmd,"providers/command",replyHandler)
		}
			
	}
}